### PR TITLE
Full version support

### PR DESCRIPTION
**Pull request by nwilging**
Includes files to support all ERN versions (341, 381-383, 41, 411).

Large feature update to `master` so we can release a tagged version and use that in composer.

### CODE REVIEW

**Comment by joelatgrayv** [comment]
Looks good from what I can tell. 

- The composer.json file needs the homepage updated
- Can you please add a workflow to run phpunit?
- I was getting some test failures

```
There were 2 errors:

1) DedexBundle\Tests\Controller\ParserControllerTest::testSample001
Error: Object of class DateTime could not be converted to string

/Users/joelsaltzman/GrayV/repos/dedex/src/Entity/Ern382/EventDateType.php:112
/Users/joelsaltzman/GrayV/repos/dedex/tests/Controller/ParserControllerTest.php:98

2) DedexBundle\Tests\Controller\SimplifiersTest::testSimpleAlbum
Error: Call to a member function format() on null

/Users/joelsaltzman/GrayV/repos/dedex/tests/Simplifiers/SimplifiersTest.php:38
```

Just a note, I had to run `composer update` to get the dependencies to install, I'm not sure if that had an effect on the tests. I didn't commit.


```
 Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laminas/laminas-code is locked to version 4.7.0 and an update of this package was not requested.
    - laminas/laminas-code 4.7.0 requires php >=7.4, <8.2 -> your php version (8.2.8) does not satisfy that requirement.
  Problem 2
    - laminas/laminas-code 4.7.0 requires php >=7.4, <8.2 -> your php version (8.2.8) does not satisfy that requirement.
    - goetas-webservices/xsd2php 0.4.5 requires laminas/laminas-code ^3.3.2|^4.0 -> satisfiable by laminas/laminas-code[4.7.0].
    - goetas-webservices/xsd2php is locked to version 0.4.5 and an update of this package was not requested.
```

**Comment by carlos-grayv** [comment]
This is a big pull request 🤪, but looks good for me (just pending the tests mentioned by Joel).

Just a question, do we have a confluence documentation with the step to set the local environment working with tabasco project?

**Comment by nwilging** [comment]
> This is a big pull request 🤪, but looks good for me (just pending the tests mentioned by Joel).
> 
> Just a question, do we have a confluence documentation with the step to set the local environment working with tabasco project?

yeah it's mostly adding all those DTO style classes 🤯

**Comment by nwilging** [comment]
> Looks good from what I can tell.
> 
> * The composer.json file needs the homepage updated
> * Can you please add a workflow to run phpunit?
> * I was getting some test failures
> 
> ```
> There were 2 errors:
> 
> 1) DedexBundle\Tests\Controller\ParserControllerTest::testSample001
> Error: Object of class DateTime could not be converted to string
> 
> /Users/joelsaltzman/GrayV/repos/dedex/src/Entity/Ern382/EventDateType.php:112
> /Users/joelsaltzman/GrayV/repos/dedex/tests/Controller/ParserControllerTest.php:98
> 
> 2) DedexBundle\Tests\Controller\SimplifiersTest::testSimpleAlbum
> Error: Call to a member function format() on null
> 
> /Users/joelsaltzman/GrayV/repos/dedex/tests/Simplifiers/SimplifiersTest.php:38
> ```
> 
> Just a note, I had to run `composer update` to get the dependencies to install, I'm not sure if that had an effect on the tests. I didn't commit.
> 
> ```
>  Installing dependencies from lock file (including require-dev)
> Verifying lock file contents can be installed on current platform.
> Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
> Your lock file does not contain a compatible set of packages. Please run composer update.
> 
>   Problem 1
>     - laminas/laminas-code is locked to version 4.7.0 and an update of this package was not requested.
>     - laminas/laminas-code 4.7.0 requires php >=7.4, <8.2 -> your php version (8.2.8) does not satisfy that requirement.
>   Problem 2
>     - laminas/laminas-code 4.7.0 requires php >=7.4, <8.2 -> your php version (8.2.8) does not satisfy that requirement.
>     - goetas-webservices/xsd2php 0.4.5 requires laminas/laminas-code ^3.3.2|^4.0 -> satisfiable by laminas/laminas-code[4.7.0].
>     - goetas-webservices/xsd2php is locked to version 0.4.5 and an update of this package was not requested.
> ```

pushed `composer update` and the json changes

working on the test failure

we aren't using the "simplifiers" currently so it won't cause problems on our end, but they _should_ work so i will debug that.

**Comment by carlos-grayv** [comment]
> > This is a big pull request 🤪, but looks good for me (just pending the tests mentioned by Joel).
> > Just a question, do we have a confluence documentation with the step to set the local environment working with tabasco project?
> 
> yeah it's mostly adding all those DTO style classes 🤯

Great work! 👏🏼

**Comment by nwilging** [comment]
@carlos-grayv as far as setup docs I think those are all in the Tabasco readme

**Comment by nwilging** [comment]
@joelatgrayv  all fixed up

**Review by joelatgrayv — APPROVED** [review]

**Pull request merged**
